### PR TITLE
Updated Conditions

### PR DESCRIPTION
**Pull request by CandyFreak2**

### CODE REVIEW

**Comment by ChappiePie** [comment]
do more conditions 🔫

**Comment by ChappiePie** [comment]
do more 🔫

**Comment by CandyFreak2** [comment]
What do you want me to do?

**Comment by ChappiePie** [comment]
conditions

**Comment by CandyFreak2** [comment]
😠 no poopy chappie

**Comment by CandyFreak2** [comment]
Accept push or perish by shitting bricks...

**Comment by ChappiePie** [comment]
oh no

**Pull request merged**
